//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminMensajeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_COLONIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEN_COLONIA()
        {
            this.OPE_PUNTOENTREC = new HashSet<OPE_PUNTOENTREC>();
        }
    
        public int IdColonia { get; set; }
        public int IdCodigoP { get; set; }
        public int IdMunicipio { get; set; }
        public string Colonia { get; set; }
    
        public virtual GEN_CODIGOPOSTAL GEN_CODIGOPOSTAL { get; set; }
        public virtual GEN_MUNICIPIO GEN_MUNICIPIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_PUNTOENTREC> OPE_PUNTOENTREC { get; set; }
    }
}
