//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminMensajeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEN_USUARIO()
        {
            this.OPE_GUIA = new HashSet<OPE_GUIA>();
            this.OPE_SOLICITUD = new HashSet<OPE_SOLICITUD>();
            this.GEN_COMENSUGER = new HashSet<GEN_COMENSUGER>();
        }
    
        public int IdUsuario { get; set; }
        public int IdPuntoEntRec { get; set; }
        public int TipoUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string CorreoUsuario { get; set; }
        public bool CambiarContrasena { get; set; }
        public bool EstatusUsuario { get; set; }
    
        public virtual OPE_PUNTOENTREC OPE_PUNTOENTREC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_GUIA> OPE_GUIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_SOLICITUD> OPE_SOLICITUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_COMENSUGER> GEN_COMENSUGER { get; set; }
    }
}
