//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminMensajeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_EMAILCONGIF
    {
        public int IdEmailConfig { get; set; }
        public string Remitente { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public string ContrasenaEmail { get; set; }
        public string SMTPHost { get; set; }
        public int SMTPPort { get; set; }
        public bool SSL { get; set; }
        public bool EstatusEMail { get; set; }
    }
}
