//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminMensajeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_PUNTOENTREC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPE_PUNTOENTREC()
        {
            this.GEN_USUARIO = new HashSet<GEN_USUARIO>();
            this.OPE_CONTACTO = new HashSet<OPE_CONTACTO>();
            this.OPE_SOLICITUDPUNTOSENTREC = new HashSet<OPE_SOLICITUDPUNTOSENTREC>();
        }
    
        public int IdPuntoEntRec { get; set; }
        public int IdClientProvee { get; set; }
        public int IdColonia { get; set; }
        public string DescripcionPunto { get; set; }
        public int TipoPunto { get; set; }
        public string ContactoPunto { get; set; }
        public Nullable<System.TimeSpan> HoraDePunto { get; set; }
        public Nullable<System.TimeSpan> HoraHaPunto { get; set; }
        public string CallePunto { get; set; }
        public string NoIntPunto { get; set; }
        public string NoExtPunto { get; set; }
        public string Referencia { get; set; }
        public string ObsPunto { get; set; }
        public bool EstatusPunto { get; set; }
    
        public virtual GEN_COLONIA GEN_COLONIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_USUARIO> GEN_USUARIO { get; set; }
        public virtual OPE_CLIENTPROVEE OPE_CLIENTPROVEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_CONTACTO> OPE_CONTACTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_SOLICITUDPUNTOSENTREC> OPE_SOLICITUDPUNTOSENTREC { get; set; }
    }
}
