//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminMensajeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_SOLICITUDPRODUCTO
    {
        public int IdSolicitudProducto { get; set; }
        public int IdSolicitud { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public bool Recibido { get; set; }
        public string Receptor { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string ObsProducto { get; set; }
    
        public virtual GEN_UNIDAD GEN_UNIDAD { get; set; }
        public virtual OPE_SOLICITUD OPE_SOLICITUD { get; set; }
    }
}
