//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminMensajeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_SOLICITUD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPE_SOLICITUD()
        {
            this.OPE_SOLICITUDPRODUCTO = new HashSet<OPE_SOLICITUDPRODUCTO>();
            this.OPE_SOLICITUDPUNTOSENTREC = new HashSet<OPE_SOLICITUDPUNTOSENTREC>();
        }
    
        public int IdSolicitud { get; set; }
        public int IdUsuario { get; set; }
        public int IdClientProvee { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Emergencia { get; set; }
        public bool EstatusSolicitud { get; set; }
    
        public virtual GEN_USUARIO GEN_USUARIO { get; set; }
        public virtual OPE_CLIENTPROVEE OPE_CLIENTPROVEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_SOLICITUDPRODUCTO> OPE_SOLICITUDPRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_SOLICITUDPUNTOSENTREC> OPE_SOLICITUDPUNTOSENTREC { get; set; }
    }
}
