//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminMensajeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_SOLICITUDPUNTOSENTREC
    {
        public int IdSolicitudPuntosEntRec { get; set; }
        public int IdSolicitud { get; set; }
        public int IdPuntoEntRec { get; set; }
        public Nullable<int> IdGuia { get; set; }
        public int TipoPunto { get; set; }
        public System.DateTime FechaProgramada { get; set; }
        public string ObsPuntosEntRec { get; set; }
        public Nullable<System.DateTime> FechaReal { get; set; }
        public string FirmaPuntosEntRec { get; set; }
        public string FotoPuntosEntRec { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public bool Problema { get; set; }
        public string ObsProblema { get; set; }
        public bool EstatusPuntosEntRec { get; set; }
    
        public virtual OPE_GUIA OPE_GUIA { get; set; }
        public virtual OPE_SOLICITUD OPE_SOLICITUD { get; set; }
        public virtual OPE_PUNTOENTREC OPE_PUNTOENTREC { get; set; }
    }
}
