//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminMensajeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_REPORTE
    {
        public int NoEnvio { get; set; }
        public string Folio { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int Estatus { get; set; }
        public string Solicitante { get; set; }
        public string Producto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Receptor { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string CategoriaRemitente { get; set; }
        public string RazonSocialRemitente { get; set; }
        public string DescripcionRemitente { get; set; }
        public string ContactoRemitente { get; set; }
        public string CalleRemitente { get; set; }
        public string NoExtRemitente { get; set; }
        public string NointRemitente { get; set; }
        public string ReferenciaRemitente { get; set; }
        public string ColoniaRemitente { get; set; }
        public string CodigoPostalRemitente { get; set; }
        public string MunicipioRemitente { get; set; }
        public string EstadoRemitente { get; set; }
        public string PaisRemitente { get; set; }
        public Nullable<System.DateTime> FechaEntregaEstimada { get; set; }
        public string DestinatarioEntrega { get; set; }
        public string CategoriaEntrega { get; set; }
        public string RazonSocialEntrega { get; set; }
        public string DescripcionEntrega { get; set; }
        public string ContactoEntrega { get; set; }
        public string DirecionCompletaEntrega { get; set; }
        public string CalleEntrega { get; set; }
        public string NoExtEntrega { get; set; }
        public string NointEntrega { get; set; }
        public string ReferenciaEntrega { get; set; }
        public string ColoniaEntrega { get; set; }
        public string CodigoPostalEntrega { get; set; }
        public string MunicipioEntrega { get; set; }
        public string EstadoEntrega { get; set; }
        public string PaisEntrega { get; set; }
        public Nullable<System.DateTime> FechaAsignada { get; set; }
        public string MensajeroAsignado { get; set; }
        public string ReferenciaExterna { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
    }
}
